### ISSUE TITLE
BEGIN-END

### ISSUE THREAD

**Issue by BNNorman** [HullPixelbot/HullOS#1]
Looking through your spec Rob - Are BEGIN and END really needed? Surely IF-ELSE-ENDIF puts boundaries on the code. Also possible are WHILE-WEND, FOREVER-ENDFOREVER.

This would mean that indented code is optional (I hate python's indenting - so easy to get out of kilter).

**Comment by CrazyRobMiles** [comment]
Good comments. I gave up on IF - ELSE - ENDIF type constructions when I kept forgetting them as I was writing the code. 

I've actually reached the scary point where I quite like Python's indenting, and it occurred to me that if I want to use my language as a stepping stone to Python it might be a good idea to use indenting. If I use indenting I need begin-end otherwise I don't know when to close off loops.

**Comment by BNNorman** [comment]
I got the indentation working so no need for WEND, ENDFOREVER or ENDIF. BEGIN and END are not really required (as per Python) but if BEGIN is used the lexical analyser expects an indented statement to follow.

**Comment by CrazyRobMiles** [comment]
Good stuff. Indenting text after a BEGIN makes a lot of sense, I'll see if
I can modify the HullOs code to support that. f

**Comment by BNNorman** [comment]
Ok.
